Repository AY2223S2-CS2103T-W12-1/tp, pull requests merged in 2023-03, with the labels that each got.

#76 Refactor storage classes and update testcases
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/FriendlyLink.java
  src/main/java/seedu/address/model/person/Elderly.java
  src/main/java/seedu/address/storage/FriendlyLinkStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedPair.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonAppStorage.java
  src/main/java/seedu/address/storage/JsonFriendlyLinkStorage.java
  src/main/java/seedu/address/storage/JsonSerializable.java
  src/main/java/seedu/address/storage/JsonSerializableFriendlyLink.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/elderly/ElderlyStorage.java
  src/main/java/seedu/address/storage/elderly/JsonAdaptedElderly.java
  src/main/java/seedu/address/storage/elderly/JsonElderlyStorage.java
  src/main/java/seedu/address/storage/elderly/JsonSerializableElderly.java
  src/main/java/seedu/address/storage/volunteer/JsonAdaptedVolunteer.java
  src/main/java/seedu/address/storage/volunteer/JsonSerializableVolunteer.java
  src/main/java/seedu/address/storage/volunteer/JsonVolunteerStorage.java
  src/main/java/seedu/address/storage/volunteer/VolunteerStorage.java
  src/test/data/JsonElderlyStorageTest/invalidAndValidElderly.json
  src/test/data/JsonElderlyStorageTest/invalidElderly.json
  src/test/data/JsonElderlyStorageTest/notJsonFormatElderly.json
  src/test/data/JsonVolunteerStorageTest/invalidAndValidVolunteer.json
  src/test/data/JsonVolunteerStorageTest/invalidVolunteer.json
  src/test/data/JsonVolunteerStorageTest/notJsonFormatVolunteer.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteElderlyCommandTest.java
  src/test/java/seedu/address/model/pair/PairTest.java
  src/test/java/seedu/address/model/person/ElderlyTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonElderlyStorageTest.java
  src/test/java/seedu/address/storage/JsonFriendlyLinkStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableFriendlyLinkTest.java
  src/test/java/seedu/address/storage/JsonVolunteerStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/PairBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalElderly.java
  src/test/java/seedu/address/testutil/TypicalPairs.java
Labels: priority.High

#89 Add more tests for pair
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddPairCommand.java
  src/main/java/seedu/address/logic/commands/DeletePairCommand.java
  src/main/java/seedu/address/model/FriendlyLink.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/pair/JsonAdaptedPair.java
  src/main/java/seedu/address/storage/pair/JsonSerializablePair.java
  src/test/data/JsonSerializablePairTest/duplicatePairs.json
  src/test/data/JsonSerializablePairTest/invalidPair.json
  src/test/data/JsonSerializablePairTest/typicalPairs.json
  src/test/java/seedu/address/logic/commands/AddPairCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeletePairTest.java
  src/test/java/seedu/address/logic/commands/EditElderlyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditElderlyDescriptorTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddElderlyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditElderlyCommandParserTest.java
  src/test/java/seedu/address/model/pair/PairTest.java
  src/test/java/seedu/address/model/person/ElderlyTest.java
  src/test/java/seedu/address/storage/JsonPairStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializablePairTest.java
  src/test/java/seedu/address/testutil/FriendlyLinkBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalElderly.java
  src/test/java/seedu/address/testutil/TypicalPairs.java
Labels: priority.Medium, severity.Low

#101 Add default predicate for filtered pair list
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High

#109 Add hash code methods
  README.md
  src/main/java/seedu/address/logic/commands/AddElderlyCommand.java
  src/main/java/seedu/address/logic/commands/AddPairCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteElderlyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditElderlyCommand.java
  src/main/java/seedu/address/logic/commands/EditVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/util/EditElderlyDescriptor.java
  src/main/java/seedu/address/logic/commands/util/EditPersonDescriptor.java
  src/main/java/seedu/address/logic/commands/util/EditVolunteerDescriptor.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/exceptions/ElderlyNotFoundException.java
  src/main/java/seedu/address/model/person/exceptions/VolunteerNotFoundException.java
Labels: severity.Low

#116 Fix bug causing null pointer exception on add_pair
  src/main/java/seedu/address/logic/commands/DeleteElderlyCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/FriendlyLink.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/pair/JsonAdaptedPair.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/FriendlyLinkTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
Labels: type.Bug, priority.High, severity.Medium

#115 Update pair architecture in developerGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/developerGuide/Pair.puml
  docs/images/developerGuide/Pair.png
Labels: type.Documentation, priority.High

#122 Update version number to 1.3
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#123 Add DG for Storage class
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/developerGuide/StorageClassDiagram.png
Labels: type.Documentation, priority.High

#125 Change logging message
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: severity.Low

#107 Add Summarise Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Summary.java
  src/main/java/seedu/address/logic/aggregatefunction/AggregateFunction.java
  src/main/java/seedu/address/logic/aggregatefunction/Count.java
  src/main/java/seedu/address/logic/aggregatefunction/GroupedCount.java
  src/main/java/seedu/address/logic/aggregatefunction/MaxCount.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/FriendlyLinkParser.java
  src/test/java/seedu/address/logic/SummaryTest.java
  src/test/java/seedu/address/logic/aggregatefunction/CountTest.java
  src/test/java/seedu/address/logic/aggregatefunction/MaxCountTest.java
  src/test/java/seedu/address/logic/commands/StatsCommandTest.java
  src/test/java/seedu/address/logic/parser/FriendlyLinkParserTest.java
Labels: type.Documentation, type.Enhancement, type.Story, priority.Medium

#124 Update find command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/developerGuide/FindSequenceDiagram.png
Labels: type.Documentation, priority.High

#146 Update architecture of FriendlyLink in developerGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#112 Add `CommandRecommendationEngine`
  docs/DeveloperGuide.md
  docs/diagrams/CommandRecommendationActivityDiagram.puml
  docs/images/developerGuide/CommandRecommendationActivityDiagram.png
  src/main/java/seedu/address/logic/commands/AddElderlyCommand.java
  src/main/java/seedu/address/logic/commands/AddPairCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandInfo.java
  src/main/java/seedu/address/logic/commands/CommandRecommendationEngine.java
  src/main/java/seedu/address/logic/commands/DeleteElderlyCommand.java
  src/main/java/seedu/address/logic/commands/DeletePairCommand.java
  src/main/java/seedu/address/logic/commands/DeleteVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditElderlyCommand.java
  src/main/java/seedu/address/logic/commands/EditVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/StatsCommand.java
  src/main/java/seedu/address/logic/parser/AddElderlyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPairCommandParser.java
  src/main/java/seedu/address/logic/parser/AddVolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ClearCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteElderlyCommandParser.java
  src/main/java/seedu/address/logic/parser/DeletePairCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteVolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditElderlyCommandParser.java
  src/main/java/seedu/address/logic/parser/EditVolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/ExitCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/HelpCommandParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandRecommendationEngineTest.java
Labels: type.Enhancement, priority.Medium

#151 Update developer guide for UI Component
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/developerGuide/UiClassDiagram.png
Labels: priority.High

#154 Update architecture sequence diagram and appendix of DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation, priority.High

#164 Update developerGuide.md
  docs/DeveloperGuide.md
  docs/diagrams/developerGuide/StatsCommandClassDiagram.puml
  docs/images/developerGuide/StatsCommandClassDiagram.png
Labels: type.Documentation, priority.High

#153 Update UI
  src/main/java/seedu/address/model/person/information/Address.java
  src/main/java/seedu/address/model/person/information/Age.java
  src/main/java/seedu/address/model/person/information/AvailableDate.java
  src/main/java/seedu/address/model/person/information/Email.java
  src/main/java/seedu/address/model/person/information/Name.java
  src/main/java/seedu/address/model/person/information/Nric.java
  src/main/java/seedu/address/model/person/information/Phone.java
  src/main/java/seedu/address/model/person/information/Region.java
  src/main/java/seedu/address/model/person/information/RiskLevel.java
  src/main/java/seedu/address/model/tag/MedicalQualificationTag.java
  src/main/java/seedu/address/ui/ElderlyCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PairCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/VolunteerCard.java
  src/main/resources/images/age.png
  src/main/resources/images/app_icon.png
  src/main/resources/images/availability.png
  src/main/resources/images/email.png
  src/main/resources/images/home-address.png
  src/main/resources/images/medical-tags.png
  src/main/resources/images/nric.png
  src/main/resources/images/paired.png
  src/main/resources/images/phone.png
  src/main/resources/images/region.png
  src/main/resources/images/tags.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ElderlyListCard.fxml
  src/main/resources/view/ElderlyListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PairListCard.fxml
  src/main/resources/view/PairListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/VolunteerListCard.fxml
  src/main/resources/view/VolunteerListPanel.fxml
Labels: priority.High

#157 Refactor is same person checks in FriendlyLink
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddElderlyCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditElderlyCommand.java
  src/main/java/seedu/address/logic/commands/EditVolunteerCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddElderlyCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddElderlyCommandTest.java
  src/test/java/seedu/address/logic/commands/AddVolunteerCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddVolunteerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditElderlyCommandTest.java
  src/test/java/seedu/address/logic/commands/EditVolunteerCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ElderlyTest.java
  src/test/java/seedu/address/model/person/VolunteerTest.java
  src/test/java/seedu/address/storage/JsonSerializableVolunteerTest.java
Labels: type.Bug

#166 Update list command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FriendlyLinkParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/FriendlyLinkParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High

#174 Update UI to improve UX
  src/main/java/seedu/address/ui/ElderlyListPanel.java
  src/main/java/seedu/address/ui/PairCard.java
  src/main/java/seedu/address/ui/PairListPanel.java
  src/main/java/seedu/address/ui/VolunteerListPanel.java
  src/main/resources/images/empty.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ElderlyListPanel.fxml
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PairListCard.fxml
  src/main/resources/view/PairListPanel.fxml
  src/main/resources/view/VolunteerListPanel.fxml
Labels: priority.High

#181 Update user guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/readMe/Ui.png
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/test/java/seedu/address/logic/commands/CommandRecommendationEngineTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Documentation, priority.High

#180 Make person fields optional
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddElderlyCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteerCommand.java
  src/main/java/seedu/address/logic/parser/AddElderlyCommandParser.java
  src/main/java/seedu/address/logic/parser/AddVolunteerCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Elderly.java
  src/main/java/seedu/address/model/person/Volunteer.java
  src/main/java/seedu/address/model/person/information/Address.java
  src/main/java/seedu/address/model/person/information/Email.java
  src/main/java/seedu/address/model/person/information/Phone.java
  src/main/java/seedu/address/model/person/information/Region.java
  src/main/java/seedu/address/model/person/information/RiskLevel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddElderlyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddVolunteerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditElderlyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditVolunteerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/information/AddressTest.java
  src/test/java/seedu/address/model/person/information/EmailTest.java
  src/test/java/seedu/address/model/person/information/PhoneTest.java
  src/test/java/seedu/address/model/person/information/RegionTest.java
  src/test/java/seedu/address/model/person/information/RiskLevelTest.java
Labels: type.Bug, priority.High

#185 Move proposed features to developerGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#186 Update available dates matching
  src/main/java/seedu/address/model/person/predicates/AvailableDatesWithinRangePredicate.java
  src/test/java/seedu/address/model/person/predicates/AvailableDatesWithinRangePredicateTest.java
Labels: type.Bug, priority.High

#193 Fix feature flaws
  README.md
  build.gradle
  docs/images/Ui.png
  docs/images/readMe/Ui.png
  src/main/java/seedu/address/logic/commands/AddElderlyCommand.java
  src/main/java/seedu/address/logic/commands/AddVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditElderlyCommand.java
  src/main/java/seedu/address/logic/commands/EditVolunteerCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/model/person/Elderly.java
  src/main/java/seedu/address/model/person/Volunteer.java
  src/main/java/seedu/address/model/person/information/Region.java
  src/main/java/seedu/address/model/person/information/RiskLevel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddElderlyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddVolunteerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditElderlyCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditVolunteerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/information/AddressTest.java
  src/test/java/seedu/address/model/person/information/EmailTest.java
  src/test/java/seedu/address/model/person/information/PhoneTest.java
  src/test/java/seedu/address/model/person/information/RegionTest.java
  src/test/java/seedu/address/model/person/information/RiskLevelTest.java
Labels: type.Bug, type.Documentation, priority.High, severity.Medium

#205 Update userGuide.md to show empty FriendlyLink
  docs/UserGuide.md
  docs/images/emptyFriendlyLink.png
Labels: type.Documentation, priority.High, severity.VeryLow
