Repository AY2223S2-CS2103T-W12-1/tp, pull requests merged in 2023-04, with the labels that each got.

#262 Update Project Portfolio
  docs/team/gohyongjing.md
Labels: type.Documentation, priority.High

#263 Add planned enhancements section
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#257 Fix acceptance test bugs
  docs/UserGuide.md
Labels: type.Documentation, priority.High, severity.Medium

#261 Improve userGuide to improve readability
  docs/UserGuide.md
  docs/images/userGuide/findStats.png
  docs/images/userGuide/icons/age.png
  docs/images/userGuide/icons/calendar.png
  docs/images/userGuide/icons/email.png
  docs/images/userGuide/icons/home-address.png
  docs/images/userGuide/icons/medical-tags.png
  docs/images/userGuide/icons/nric.png
  docs/images/userGuide/icons/phone.png
  docs/images/userGuide/icons/region.png
  docs/images/userGuide/icons/tags.png
  docs/images/userGuide/pair.png
  docs/images/userGuide/stats.png
  docs/images/userGuide/unpair.png
Labels: type.Documentation, priority.High, severity.Medium

#269 Update ppp and find sequence diagram in dg
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/images/developerGuide/FindSequenceDiagram.png
  docs/team/wz2k.md
Labels: type.Documentation

#270 Refactor region and date checks
  src/main/java/seedu/address/logic/commands/AddPairCommand.java
  src/main/java/seedu/address/logic/commands/EditElderlyCommand.java
  src/main/java/seedu/address/logic/commands/EditVolunteerCommand.java
  src/main/java/seedu/address/model/FriendlyLink.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/pair/Pair.java
  src/main/java/seedu/address/model/pair/UniquePairList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddPairCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePairCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteVolunteerCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/model/FriendlyLinkTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/pair/PairTest.java
Labels: priority.High

#275 Add descriptions to examples
  docs/UserGuide.md
Labels: type.Documentation

#271 Update documentation
  docs/UserGuide.md
  docs/diagrams/developerGuide/StatsCommandClassDiagram.puml
  docs/images/developerGuide/StatsCommandClassDiagram.png
  docs/team/gohyongjing.md
  src/main/java/seedu/address/model/FriendlyLink.java
Labels: type.Documentation, priority.High

#274 Improve Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/heeeyi.md
Labels: type.Documentation, priority.High

#279 Update userGuide.md
  docs/UserGuide.md
Labels: type.Documentation, priority.High

#283 Revert "Removed unused images"
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/ComponentManagers.png
  docs/images/LogicClassDiagram.png
  docs/images/LogicStorageDIP.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/SeEduLogo.png
  docs/images/StorageClassDiagram.png
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkNotImplemented.png
  docs/images/findAlexDavidResult.png
  docs/images/johndoe.png
  docs/images/remove/$address.png
  docs/images/request_access.png
  docs/images/tracing/StructureToolWindow.png
  docs/images/tracing/searchResultsForExecuteMethod.png
Labels: type.Documentation, priority.High, severity.High

#289 Add more instructions for manual testing
  docs/DeveloperGuide.md
Labels: priority.High

#291 Improve wording and formatting of future enhancements
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/images/userGuide/findStats.png
  docs/images/userGuide/pair.png
  docs/images/userGuide/stats.png
  docs/images/userGuide/unpair.png
Labels: type.Documentation, priority.High

#297 Update docs and code quality
  docs/DeveloperGuide.md
  docs/Logging.md
  docs/diagrams/developerGuide/FindCommandClassDiagram.puml
  docs/diagrams/developerGuide/FindSequenceDiagram.puml
  docs/images/developerGuide/FindCommandClassDiagram.png
  docs/team/wz2k.md
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddPairCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/pair/PairTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalElderly.java
Labels: priority.High
